python -m main.codesearch_fedavg \
   --client_num_in_total 64 \
   --client_num_per_round 8 \
   --comm_round 12 \
   --dataset "codesearch" \
   --language "php" \
   --train_data_file "data/store/codesearch/train_valid/php/train.txt" \
   --train_partition_file "data/store/codesearch/train_valid/php/train_partition_64.pk" \
   --partition_method niid_quantity_clients=64_beta=1.0 \
   --fl_algorithm FedAvg \
   --model_type '../../models/roberta-base' \
   --model_name '../../models/codebert-base' \
   --do_lower_case True \
   --train_batch_size 64 \
   --eval_batch_size 32 \
   --max_seq_length 200 \
   --learning_rate 1e-5 \
   --epochs 1 \
   --output_dir "tmp/fedavg_codesearch_output/" \
   --cache_dir "cache/codesearch/php_64" \
   --do_train